source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
project 'WebsocketExampleClient.xcodeproj'
inhibit_all_warnings!
#use_frameworks!

target :"WebsocketExampleClient" do

  pod "SocketRocket", '0.5.1'
  pod 'themis', '0.9.6'

end